services:
  - type: web
    name: election-cli
    env: python3
    plan: free
    buildCommand: "npm install && npm run build && pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/" 