services:
  - type: web
    name: election-game
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: / 